//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Karyawan
    {
        public int ID { get; set; }
        public string NPK { get; set; }
        public string NamaKaryawan { get; set; }
        public string JenisKelamin { get; set; }
        public Nullable<System.DateTime> TanggalLahir { get; set; }
        public string Alamat { get; set; }
        public string Email { get; set; }
        public string NoTelp { get; set; }
        public Nullable<int> ID_Role { get; set; }
        public Nullable<int> ID_Seksi { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> LastModifiedTime { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> RowStatus { get; set; }
        public string Foto { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Section Section { get; set; }
    }
}
