//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeranjangPengajuan
    {
        public int ID { get; set; }
        public int ID_Barang { get; set; }
        public string ID_Karyawan { get; set; }
        public Nullable<int> Qyt { get; set; }
    
        public virtual BarangVendor BarangVendor { get; set; }
    }
}
