//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAIS.Models
{
    using System;
    using System.Collections.Generic;

    [System.ComponentModel.DataAnnotations.MetadataType(typeof(PeminjamanMetaData))]
    public partial class Peminjaman
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Peminjaman()
        {
            this.DetailPeminjamen = new HashSet<DetailPeminjaman>();
        }
    
        public string ID { get; set; }
        public string ID_Karyawan { get; set; }
        public string ID_GA { get; set; }
        public Nullable<System.DateTime> TglPeminjaman { get; set; }
        public Nullable<System.DateTime> TglPengembalian { get; set; }
        public Nullable<System.DateTime> LastModifiedTime { get; set; }
        public string AcceptedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> IsLate { get; set; }
        public Nullable<int> Denda { get; set; }
        public string StatusDenda { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailPeminjaman> DetailPeminjamen { get; set; }
        public virtual Karyawan Karyawan { get; set; }
    }
}
