//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pengajuan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pengajuan()
        {
            this.DetailPengajuans = new HashSet<DetailPengajuan>();
        }
    
        public string ID_Pengajuan { get; set; }
        public string ID_GA { get; set; }
        public Nullable<System.DateTime> Tgl_Pengajuan { get; set; }
        public Nullable<int> TotalHarga { get; set; }
        public int StatusPengajuan { get; set; }
        public Nullable<int> SudahDibayar { get; set; }
        public string StatusFinal { get; set; }
        public Nullable<System.DateTime> LastModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailPengajuan> DetailPengajuans { get; set; }
    }
}
