//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_LaporanPeminjaman
    {
        public string ID { get; set; }
        public string NamaKaryawan { get; set; }
        public string AcceptedBy { get; set; }
        public string NamaBarang { get; set; }
        public Nullable<int> Kuantitas { get; set; }
        public string TglPeminjaman { get; set; }
        public string TglPengembalian { get; set; }
        public string StatusPeminjaman { get; set; }
    }
}
