//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_StatusPengajuan
    {
        public int ID { get; set; }
        public int StatusPengajuan { get; set; }
        public string DeskripsiTrans { get; set; }
        public Nullable<int> jumlah { get; set; }
    }
}
